name: Generate Install Script
on:
  push:
    branches: [ main ]
jobs:
  release:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 18.x ]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Get release name
        run: |
          const core = require('@actions/core');
          const releaseName = core.getInput('release_name') || github.event.release.name;
          console.log(`The release name is ${releaseName}`);
        env:
          release_name: ${{ github.event.inputs.release_name }}