name: Generate Install Script
on:
  push:
    branches: [ main ]
jobs:
  release:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 18.x ]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Override Latest Release
        run: |
          import requests
          token = '${{ secrets.TOKEN }}'
          repo = '${{ github.repository }}'
          url = f'https://api.github.com/repos/{repo}/releases/latest'
          headers = {
            'Authorization': f'token {token}',
            'Accept': 'application/vnd.github.v3+json'
          }
          response = requests.get(url, headers=headers)
          name = response.json().get('name')
          
          with open('.github/temp.sh', 'r', encoding='utf-8') as fp:
              data = fp.read().replace('{{version}}', name)
              with open('.github/temp.sh', 'w', encoding='utf-8') as _fp:
                  _fp.write(data)
                  print(data)

        shell: python
